### ISSUE TITLE
Generate aggregated coverage report containing all process definitions

### ISSUE THREAD

**Issue by tobiasbehr** [camunda-community-hub/camunda-process-test-coverage#199]
As a developer I want to have a consolidated report (containing all process tests) being generated when I run the tests on my project.

Current behaviour (v1.0.3): When I run multiple test classes, each testing a different process, I only get a report for the first test class.

As a workaround we can use a dedicated instance of `ProcessEngineCoverageExtension` for each test so that we get one report.html for each.

**Comment by rohwerj** [comment]
Extracted the issue where test classes sharing an extension do not write the report correctly into #208
