### ISSUE TITLE
Make sure licence check plugin is working

### ISSUE THREAD

**Issue by zambrovski** [camunda-community-hub/camunda-process-test-coverage#217]
Either configure the licence check with licence set, or disable the plugin completely.
Currently just disabled it from the GH workflow.

**Comment by DennisRieg** [comment]
Hello, 
I also have the problem that our tests with coverage no longer run when the Camunda license is stored. 
Greetings
Dennis

**Comment by zambrovski** [comment]
Could you have a look on that, @rohwerj ?

**Comment by DennisRieg** [comment]
[JUnit-BPM-Coverage.zip](https://github.com/camunda-community-hub/camunda-process-test-coverage/files/10740248/JUnit-BPM-Coverage.zip)

Hello Jan,
here is an example project.
The tests are green. If you put a camunda-licence.txt in the classpath (e.g. src/main/resources), there is an error when initializing the test coverage lib. 
Thank you and greetings 
Dennis

**Comment by rohwerj** [comment]
Hello @DennisRieg.
This is very strange. I ran your project locally first without and then with a camunda license on the classpath.
For me it works in both cases.
I'm also sure that it picked up the license as the following line was in the output:
21:06:49.716 [main] INFO  o.c.b.s.b.s.c.i.c.EnterLicenseKeyConfiguration - Found provided license file: camunda-license.txt
Is there something else in your setup?
Could you share the stacktrace or the output when the library fails to load?

**Comment by DennisRieg** [comment]
Hi @rohwerj, 

I've attached the full output of maven clean install. The test fails for me with Java 11, 17 and 19 on a Mac M1.

Greetings
Dennis

[output.txt](https://github.com/camunda-community-hub/camunda-process-test-coverage/files/10753013/output.txt)

**Comment by rohwerj** [comment]
Hi @DennisRieg.
This is really very strange. The error is an indicator, that the test execution listener is not correctly called at the setup of the tests.
I still cannot reproduce this problem locally. Tried with different Java versions and also tried to align the maven plugin versions with those from you log. 
Still the tests succeed whether I have a valid camunda license in the classpath or not.
I'm currently out of ideas, but will continue to try to reproduce the error locally.
Is your license only a Camunda BPM license? Or a combined license for Optimize or Cawemo also?
Could you share the first line of the license key.
In my case it's --------------- BEGIN CAMUNDA BPM LICENSE KEY --------------- so nothing secret in there.

**Comment by DennisRieg** [comment]
Hi, 
our licence starts with
--------------- BEGIN CAMUNDA BPM LICENSE KEY ---------------
hm, that is very strange.
I will try to run the example on a windows machine....
Greetings
Dennis

**Comment by DennisRieg** [comment]
Hm, 

I can't reproduce it with the same example on a windows machine... Maybe this error has nothing todo with this great lib, but with camunda on Mac M1...

Greetings
Dennis
