### ISSUE TITLE
Please make the 2.0.0 available in maven central

### ISSUE THREAD

**Issue by zambrovski** [camunda-community-hub/camunda-process-test-coverage#218]
I released 2.0.0 to Camunda Artifactory and OSS Maven Central.
Please cloe the repository in OSS and make the release available to the public.

@camunda-community-hub/devrel could you help?

**Comment by akeller** [comment]
Closed and released just now! 🚀

**Comment by zambrovski** [comment]
Will wait until it is available in Maven central and close then.

**Comment by rohwerj** [comment]
Version 2.0.0 is available in Maven Central

**Comment by dmurat** [comment]
Can you, please, provide the exact link to the maven central repository. I can't find the latest 2.0.0 artifact. Tnx.

**Comment by berndruecker** [comment]
Package has changed, so see https://mvnrepository.com/artifact/org.camunda.community.process_test_coverage

**Comment by dmurat** [comment]
@berndruecker Tnx.

I did a search at https://search.maven.org/ (https://search.maven.org/search?q=g:org.camunda.community.process_test_coverage%20AND%20a:camunda-process-test-coverage-engine-platform-7).
I guess it is not replicated there yet.

**Comment by rohwerj** [comment]
@dmurat You are right, that it's not visible on search.maven.org. We don't know why this is so. 
Please also see
https://github.com/camunda-community-hub/camunda-process-test-coverage/discussions/225
