### ISSUE TITLE
render coverage error when "<bpmn:extensionElements />" found

### ISSUE THREAD

**Issue by nesies** [camunda-community-hub/camunda-process-test-coverage#243]
when this XML block is found in a BPMN file:
<bpmn:extensionElements />

The html render the process:
-  without the coverage colors 
- with the follow stack in the console

![image](https://user-images.githubusercontent.com/107966/192502851-8f87b438-c06c-49ea-8e90-be1d9a61d561.png)

**Comment by rohwerj** [comment]
@alex-praschek maybe you can have a look at this bug?

**Comment by alex-praschek** [comment]
Hi, sure, I can take a look in the next few days. Sorry for the delay.

**Comment by rohwerj** [comment]
@nesies could you please provide the report.html and report.json, that can reproduce the error?

**Comment by rohwerj** [comment]
@nesies Please update to version 2.0.0 of the extension. When I do that for your example, it won't fail anymore.
The required dependency for this is:
    <dependency>
      <groupId>org.camunda.community.process_test_coverage</groupId>
      <artifactId>camunda-process-test-coverage-junit4-platform-7</artifactId>
      <version>2.0.0</version>
      <scope>test</scope>
    </dependency>
Afterwards the imports have to be adjusted for the Rule and ProcessConfiguration.

**Comment by nesies** [comment]
indeed, i used an old artifact, before is was moved

thank you


https://github.com/nesies/camunda-process-test-coverage.issues.243/tree/upgrade_amunda-process-test-coverage-junit4-platform_2.0.0
