### ISSUE TITLE
coverage percentage when using CallActivity

### ISSUE THREAD

**Issue by nesies** [camunda-community-hub/camunda-process-test-coverage#291]
When testing BPMN which uses CallActivity, the coverage percentage result is misleading.

How to reproduce ? 

* one BPMN "caller"
* one BPMN "called" with a ExclusiveGatway with two branches.

* one TestCase calling "called" going to the *first* branch
* one TestCase calling "called going to the *second* branch

> the coverage results will not be 100%.

```
$ git clone https://github.com/nesies/camunda-process-test-coverage-issue-291 
$ cd tests_java
$ mvn  test  2>&1 > test.log
```

Expected:
```
$ grep "coverage is" test.log |grep -E '^INFO: test\.'

INFO: test.camunda.unittest.CallWorkTestCase test class coverage is: 1.0
INFO: test.camunda.unittest.CallNothingTestCase test class coverage is: 1.0
INFO: test.camunda.unittest.CalledTestCase test class coverage is: 1.0
```

Got:
```
$ grep "coverage is" test.log |grep -E '^INFO: test\.'

INFO: test.camunda.unittest.CallWorkTestCase test class coverage is: 0.8421052631578947
INFO: test.camunda.unittest.CallNothingTestCase test class coverage is: 0.8421052631578947
INFO: test.camunda.unittest.CalledTestCase test class coverage is: 1.0
```

**Comment by rohwerj** [comment]
@nesies If I understand correctly the first and second test case use either the first or the second branch. So the result is correct as the test class doesn't cover all possible branches. Only the third test case (CalledTestCase) has test methods, that cover all possible branches of the diagram. 
What might be missing here, is an overall coverage over all test cases, but that is something that is not yet provided.

**Comment by nesies** [comment]
I have a (sub)BPMN called by several other BPMN.

In order to get 100% coverage, i have to test 100% of the (sub)BPMN in all of these BPMN.
Which is not convenient.

**Comment by rohwerj** [comment]
I understand your reasoning, but for the calculation of the coverage, we take all elements from all deployed diagrams and check how many were passed. This is not something won't change, as it would break for many other use cases and is not correct anyway.
For your scenario I have another suggestion. 
Test the called BPMN in one test class,  covering all branches. And then mock this called BPMN in all test cases, that test the calling BPMN diagrams e.g. using https://github.com/camunda-community-hub/camunda-platform-7-mockito/.
That way you have a better separation and are testing the diagrams as small units.

**Comment by nesies** [comment]
exactly what i need, thank you
