### ISSUE TITLE
Please release version 2.1.0 to Maven central

### ISSUE THREAD

**Issue by rohwerj** [camunda-community-hub/camunda-process-test-coverage#325]
@camunda-community-hub/devrel

**Comment by ingorichtsmeier** [comment]
Hi @rohwerj,

you can enable auto-release in the github workflow like here: https://github.com/camunda-community-hub/community-action-maven-release/blob/main/example-workflows/java11/deploy.yml#L37

**Comment by ingorichtsmeier** [comment]
I've pushed the release button.

**Comment by rohwerj** [comment]
@ingorichtsmeier 
Thank you. I also now set the auto-release flag for the next release
