### ISSUE TITLE
show wait states before external service tasks

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda-community-hub/camunda-process-test-coverage#39]
Create a red line to show a wait state infornt of an external service task.

**Comment by StephenOTT** [comment]
@ingorichtsmeier I was working on a style for this related to #32.  My thought was that it should be a slightly different wait state visual, than Async config as you can still apply a wait state (similar how you can apply a Async to a User Task).


Here is a example or how i was showing the difference between User Task implied aync, and the specific Async config:

![41118430-ecb2bb7a-6a5d-11e8-9516-68b297dbb048](https://user-images.githubusercontent.com/1994838/43326282-71a8e594-9186-11e8-910d-a6fcdc374730.png)


Thoughts on similar approach for external service task?

**Comment by StephenOTT** [comment]
@ingorichtsmeier here is a example i just through together from a unit test

![screen shot 2018-07-27 at 11 36 12 am](https://user-images.githubusercontent.com/1994838/43330614-b5dfa49a-9191-11e8-99c0-71b20f99b24e.png)

**Comment by StephenOTT** [comment]
@ingorichtsmeier note that with a implicit wait state (user task, external task) vs a explicit wait (async before/after configs on a Task), a implicit does not require further config of job executor in a Unit test.  But explicit requires extra job executions: Such as a User Task that is also configured as Async Before.

**Comment by rohwerj** [comment]
Currently I don't see the need for this anymore. The user should in my opinion know, that some bpmn elements come with an inherent "wait state". So only asyncBefore and asyncAfter are import to be visualized, as they are otherwise not known to the user.
