### ISSUE TITLE
Version 2.3.0 is not compatible with Camunda 7.20.0 and SpringBoot 3.x

### ISSUE THREAD

**Issue by KBGenerali** [camunda-community-hub/camunda-process-test-coverage#403]
**Setup**
- JUnit5
- Java 17
- Camunda 7.20.0 via SpringBoot
- SpringBoot 3.1.5
- camunda-process-test-coverage 2.3.0
- Testsetup via starter-platform-7 and junit5-platform-7 as described in https://github.com/camunda-community-hub/camunda-process-test-coverage/tree/master/examples/spring-starter-platform-7

**Failure**
Version 2.3.0 is not compatible with Camunda 7.20.0 and SpringBoot 3.x
Process coverage can't be asserted because it is NaN
![image](https://github.com/camunda-community-hub/camunda-process-test-coverage/assets/59023099/2569b447-e1e4-4c0f-bfc7-a5a545735684)

**How to reproduce the failure**
Failure can be reproduced by using the spring-starter-platform-7 example.
Set camunda.compile.version to 7.20.0 and spring-boot.version to 3.1.5 in camunda-process-test-coverage-root and set History Time to Live on process model to be compatible with Camunda 7.20.0.

**Expected behavior**
Process test coverage library is compatible with Camunda 7.20.0 and SpringBoot 3.1.5 and the process coverage can be collected and asserted.
Otherwise please provide information on how to configure compatibility with Camunda 7.20.0 and SpringBoot 3.1.5 with existing sources.

**Comment by rohwerj** [comment]
Fixed by Release 2.3.1
