### ISSUE TITLE
Change target folder in aggregate using camunda-process-test-coverage-report-aggregator-gradle-plugin

### ISSUE THREAD

**Issue by dcebotarenco** [camunda-community-hub/camunda-process-test-coverage#586]
I cannot find a way to override the aggregation target folder

![image](https://github.com/user-attachments/assets/2fca724c-274d-47d6-a022-3c686478f9b9)

I dont want all tests to end up in target folder so i moved them to "build/reports/tests/camunda/"

* `System.setProperty` does not work
* test system properties are not inherited
* `gradle clean test -Dcamunda-process-test-coverage.target-dir-root=build/reports/tests/camunda --rerun-tasks` not works

how can i configure the gradle extension as part of the build.gradle

**Comment by rohwerj** [comment]
It should also be possible to configure the gradle plugin via an extension section.
So for your example it should be:
`
aggregateProcessTestCoverage {
    outputDirectory = build/reports/tests/camunda/all
}
`

**Comment by dcebotarenco** [comment]
![image](https://github.com/user-attachments/assets/905df70c-283e-4d33-be7e-209339445bda)

I think that the coverage does not know to read the reports other then from the target folder. I spotted this here:
![image](https://github.com/user-attachments/assets/47c2bc95-7278-41fb-b4e7-ec419dea7e70)

I tried:
```
aggregateProcessTestCoverage {
    beforeEvaluate {
        System.property "camunda-process-test-coverage.target-dir-root", "build/reports/tests/camunda/"
    }
    outputDirectory = 'build/reports/tests/camunda/all'
}
```
which did nothing. The output directory i guess has no impact here. Same thing happens with `-D`

![image](https://github.com/user-attachments/assets/0246cd1e-9cb7-4a3f-9f70-12123b1269e4)

**Comment by rohwerj** [comment]
Now there's a new way to configure the report directory and the output directory for the aggregate report.
See the configuration section in the documentation.

**Comment by dcebotarenco** [comment]
Hey, thanks for your effort! I will communicate the great news to my teammates
